// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkkrsEF-ZeZelaE7qiC2f0a_GIwwGLOTs',
    appId: '1:929336653793:web:d3fe12c8eefc0478ca44a0',
    messagingSenderId: '929336653793',
    projectId: 'coachyp-ddae3',
    authDomain: 'coachyp-ddae3.firebaseapp.com',
    storageBucket: 'coachyp-ddae3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqSFo77c6HXaI4jVS8KLifHd0FRWv7Ur8',
    appId: '1:929336653793:android:6a0273d42d091646ca44a0',
    messagingSenderId: '929336653793',
    projectId: 'coachyp-ddae3',
    storageBucket: 'coachyp-ddae3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr-cEUPqNzUQW9xFBrw3qzhVNdY5SqAFE',
    appId: '1:929336653793:ios:5cf2a73a73192c1fca44a0',
    messagingSenderId: '929336653793',
    projectId: 'coachyp-ddae3',
    storageBucket: 'coachyp-ddae3.firebasestorage.app',
    iosBundleId: 'com.example.coachyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr-cEUPqNzUQW9xFBrw3qzhVNdY5SqAFE',
    appId: '1:929336653793:ios:5cf2a73a73192c1fca44a0',
    messagingSenderId: '929336653793',
    projectId: 'coachyp-ddae3',
    storageBucket: 'coachyp-ddae3.firebasestorage.app',
    iosBundleId: 'com.example.coachyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkkrsEF-ZeZelaE7qiC2f0a_GIwwGLOTs',
    appId: '1:929336653793:web:ff990c9645b0abd0ca44a0',
    messagingSenderId: '929336653793',
    projectId: 'coachyp-ddae3',
    authDomain: 'coachyp-ddae3.firebaseapp.com',
    storageBucket: 'coachyp-ddae3.firebasestorage.app',
  );

}