// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiHgOozkHUA0HmBqU-Pp-Y3GuYlorLDzY',
    appId: '1:1045550339552:web:e5d2977700051083a2c785',
    messagingSenderId: '1045550339552',
    projectId: 'coachy-afc9a',
    authDomain: 'coachy-afc9a.firebaseapp.com',
    storageBucket: 'coachy-afc9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSmpw1EiMKEKOunrWfzkYoDVihVqro_sc',
    appId: '1:1045550339552:android:5b8ab01a9a8daec0a2c785',
    messagingSenderId: '1045550339552',
    projectId: 'coachy-afc9a',
    storageBucket: 'coachy-afc9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-XrOY64gFf5hAvLybfbZI7OuWeuIA5P8',
    appId: '1:1045550339552:ios:dff3da5fb62c569ea2c785',
    messagingSenderId: '1045550339552',
    projectId: 'coachy-afc9a',
    storageBucket: 'coachy-afc9a.firebasestorage.app',
    iosClientId: '1045550339552-693l4ng0nq0li7m3lr0m4caisqau0t5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.coachy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-XrOY64gFf5hAvLybfbZI7OuWeuIA5P8',
    appId: '1:1045550339552:ios:dff3da5fb62c569ea2c785',
    messagingSenderId: '1045550339552',
    projectId: 'coachy-afc9a',
    storageBucket: 'coachy-afc9a.firebasestorage.app',
    iosClientId: '1045550339552-693l4ng0nq0li7m3lr0m4caisqau0t5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.coachy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiHgOozkHUA0HmBqU-Pp-Y3GuYlorLDzY',
    appId: '1:1045550339552:web:d5e8cb752f2271b4a2c785',
    messagingSenderId: '1045550339552',
    projectId: 'coachy-afc9a',
    authDomain: 'coachy-afc9a.firebaseapp.com',
    storageBucket: 'coachy-afc9a.firebasestorage.app',
  );
}
